### ISSUE TITLE
Random null pointer exceptions for somebody

### ISSUE THREAD

**Issue by murgo** [murgo/IrssiNotifier#149]
java.lang.NullPointerException
 at fi.iki.murgo.irssinotifier.MessagePagerAdapter.createChannel(MessagePagerAdapter.java:98)
 at fi.iki.murgo.irssinotifier.MessagePagerAdapter.instantiateItem(MessagePagerAdapter.java:43)
 at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:800)
 at android.support.v4.view.ViewPager.populate(ViewPager.java:929)
 at android.support.v4.view.ViewPager.populate(ViewPager.java:880)
 at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:433)
 at fi.iki.murgo.irssinotifier.IrssiNotifierActivity.refreshUi(IrssiNotifierActivity.java:284)
 at fi.iki.murgo.irssinotifier.IrssiNotifierActivity.access$300(IrssiNotifierActivity.java:27)
 at fi.iki.murgo.irssinotifier.IrssiNotifierActivity$1.doStuff(IrssiNotifierActivity.java:163)
 at fi.iki.murgo.irssinotifier.IrssiNotifierActivity$1.doStuff(IrssiNotifierActivity.java:158)
 at fi.iki.murgo.irssinotifier.DataAccessTask.onPostExecute(DataAccessTask.java:59)
 at fi.iki.murgo.irssinotifier.DataAccessTask.onPostExecute(DataAccessTask.java:10)
 at android.os.AsyncTask.finish(AsyncTask.java:631)
 at android.os.AsyncTask.access$600(AsyncTask.java:177)
 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:5226)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by murgo** [comment]
Nah, too rare to fix.
